# hooks.py
import os, re

GENERIC = {"overview", "index", "home"}

def _filename_to_title(src_path: str) -> str:
    base = os.path.splitext(os.path.basename(src_path))[0]
    title = re.sub(r'[_\-]+', ' ', base).strip()
    title = re.sub(r'\s+', ' ', title)
    return title

def _is_tag_line(line: str) -> bool:
    # Lines like "#npc #coven" or "#Falcrest" (no space after '#') count as tag-only lines.
    tokens = line.strip().split()
    return bool(tokens) and all(t.startswith("#") and not t.startswith("# ") for t in tokens)

# --- Obsidian [[Wiki Links]] -> Markdown links --------------------------------

# Matches:
#   [[Target]]
#   [[Target|Label]]
#   [[Folder/Sub Page]]
#   [[Page#Section]]
#   [[Page|Nice Label#Section]]  (label may include #; we handle anchor from target)
WIKI_LINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#([^\]|]+))?(?:\|([^\]]+))?\]\]")

def _wiki_target_to_href(target: str, anchor: str | None) -> str:
    """
    Convert an Obsidian wiki target to a MkDocs-friendly href.
    - Keep spaces (Markdown allows them; MkDocs resolves to the right page).
    - Strip trailing .md if present.
    - Normalize slashes.
    - With use_directory_urls: true, linking to 'Page' or 'Folder/Page' is fine;
      adding a trailing '/' is also fine but not required.
    """
    t = target.strip()
    t = t.replace("\\", "/")
    if t.lower().endswith(".md"):
        t = t[:-3]
    href = t
    if anchor:
        # MkDocs lowercases and hyphenizes autogenerated ids, but user anchors might be explicit.
        # We'll pass through as provided; users can add {#id} headers if needed.
        href = f"{href}#{anchor.strip()}"
    return href

def _replace_wiki_links(markdown: str) -> str:
    def _repl(m: re.Match):
        target = m.group(1).strip()
        anchor = m.group(2).strip() if m.group(2) else None
        label  = m.group(3).strip() if m.group(3) else target
        href = _wiki_target_to_href(target, anchor)
        return f"[{label}]({href})"
    return WIKI_LINK_RE.sub(_repl, markdown)

# --- MkDocs hook ---------------------------------------------------------------

def on_page_markdown(markdown, page, config, files):
    """
    1) Force page meta title and visible H1 to the filename (nice humanized).
    2) Keep leading tag lines visible but never as titles.
    3) Convert Obsidian [[Wiki Links]] into normal Markdown links.
    """
    desired = _filename_to_title(page.file.src_path)

    # Convert [[Wiki Links]] before any structure edits
    markdown = _replace_wiki_links(markdown)

    # Rewrite markdown so the first *content* H1 matches `desired`
    lines = markdown.splitlines()

    # skip leading blanks
    i = 0
    while i < len(lines) and lines[i].strip() == "":
        i += 1

    # gather leading tag-only lines
    j = i
    tag_lines = []
    while j < len(lines) and _is_tag_line(lines[j]):
        tag_lines.append(lines[j])
        j += 1

    # find first real H1 AFTER tag lines ("# Heading" with a space)
    first_h1_idx = None
    first_h1_text = ""
    for k in range(j, len(lines)):
        m = re.match(r'^\s*#\s+(.*)$', lines[k])
        if m:
            first_h1_idx = k
            first_h1_text = m.group(1).strip()
            break

    new = []
    # Meta title for Material / breadcrumbs
    page.title = desired

    # Always make the first visible H1 our desired title
    new.append(f"# {desired}")
    new.append("")

    # Re-add tag lines under the title (keeps them visible, but no longer hijack the title)
    new.extend(tag_lines)
    if tag_lines:
        new.append("")

    # Build the rest of the document, skipping the old first H1 if it existed
    rest_start = j
    if first_h1_idx is not None:
        if first_h1_text.lower() in GENERIC or first_h1_text != desired:
            rest_start = first_h1_idx + 1

    if rest_start < len(lines) and lines[rest_start].strip():
        new.append("")

    new.extend(lines[rest_start:])

    return "\n".join(new).rstrip() + "\n"
