site_name: Terrondar Wiki
site_url: https://jdavies1207.github.io/terrondar-wiki/
use_directory_urls: true
theme:
  name: material
  extra:
    base_url: /terrondar-wiki/
  features:
    #- navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - toc.integrate
    - content.code.copy

plugins:
  - search
  - awesome-pages

hooks:
  - hooks.py

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - tables
  - md_in_html
  - pymdownx.saneheaders
  # Add other main categories and pages here
